package ru.risad.test.PIRRoadFullRepair;

// Generated by Selenium IDE
import org.testng.annotations.Test;
import ru.risad.test.TestBase;

public class H_DeleteOPWinPIRRoadFullRepairStateInFormFKU extends TestBase {

    @Test
    public void testDeleteOPWinPIRRoadFullRepairStateInFormFKU() {
        //Создание ОПР под учетной записью с ролью "пользователь ФКУ"
        gotoResourse(baseURL);
        login("baykal01", "Orator16");
        choiceSection("Планирование");
        choiceYear(startYear);
        choiseProgramWork("PIRRoadFullRepair"); // "PIRRoadFullRepair" - еще одна программа работ, в которой сохраняются данные.
//      Создание объекта программы работ
        pushCreateOPRandSaveWindow();
        fillTopFormOPRPIR("ФКУ Упрдор «Енисей»", "Республика Тыва", "Устройство защитных слоев", "11", "22", "33", "44", "24", startYear);
        addAndFillCorrection("На вновь начинаемый объект", "09.02.2020", "123");
        createObjectWork("ФКУ Упрдор «Енисей»", "'Республика Тыва'", "\"Енисей\" Красноярск - Абакан - Кызыл - Чадан - Хандагайты - граница с Монголией'", "12", "111", "21", "222", "Ремонт 12.12.2012", "444", "1 категоря");
        saveOPRandCloseWindow();
        refreshCurrentWindow();
        findNameObject(nameObject);
        logout();

        login("baykal01", "Orator16");
        choiceSection("Планирование");
        choiceYear(startYear);
        choiseProgramWork("PIRRoadFullRepair");
        clickDeleteOPW(nameObject);
        fillDeleteCorrection();
        refreshCurrentWindow();
//        Тут еще надо добавить проверку на отсутствие ОПр в гриде программы работ
        logout();
    }

}
