package ru.risad.test;

// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;
import java.util.*;
import java.util.concurrent.TimeUnit;

public class CreateObjectProgrammWork_PWstatusInDevelopment extends TestBase {

    @Test
    public void CreateOPRPRstInDev() {
        gotoResourse(baseURL);
        login("baykal01", "Orator16");
        choiceSection();
        choiceYear("2029");
        choiseProgramWork();
        createObjectProgramWork();
    }

}
