package ru.risad.test;

// Generated by Selenium IDE
import org.testng.annotations.Test;

public class CreateObjectProgrammWork extends TestBase {

    @Test
    public void testCreateOPRPR() {
        gotoResourse(baseURL);
        login("baykal01", "Orator16");
        choiceSection("Планирование");
        choiceYear("2020");
        choiseProgramWork("PIRRoadFullRepair"); // "PIRRoadRepair" - еще одна программа работ, в которой сохраняются данные.
        createProgramWorkIfNotCreatedLater();
        createObjectProgramWork();
    }

//    @Test
//    public void testCreateOPRPRstInDev_1() {
//        gotoResourse(baseURL);
//        login("baykal01", "Orator16");
//        choiceSection("Планирование");
//        choiceYear("2030");
//        choiseProgramWork("PIRRoadRepair"); // "PIRRoadRepair" - еще одна программа работ, в которой сохраняются данные.
//        createProgramWorkIfNotCreatedLater();
//        createObjectProgramWorkInDev();
//    }


}
