package ru.risad.test;

// Generated by Selenium IDE
import org.testng.annotations.Test;

public class CreateObjectProgrammWorkPWstatusInDev extends TestBase {

    @Test
    public void testCreateOPRPRstInDev() {
        gotoResourse(baseURL);
        login("baykal01", "Orator16");
        choiceSection("Планирование");
        choiceYear("2034");
        choiseProgramWork("PIRRoadFullRepair"); // "PIRRoadRepair" - еще одна программа работ, в которой сохраняются данные.
        createProgramWorkIfNotCreatedLater();
        createObjectProgramWorkInDev();
    }

    @Test
    public void testCreateOPRPRstInDev_1() {
        gotoResourse(baseURL);
        login("baykal01", "Orator16");
        choiceSection("Планирование");
        choiceYear("2030");
        choiseProgramWork("PIRRoadRepair"); // "PIRRoadRepair" - еще одна программа работ, в которой сохраняются данные.
        createProgramWorkIfNotCreatedLater();
        createObjectProgramWorkInDev();
    }
    

}
