package ru.risad.test;

// Generated by Selenium IDE
import org.testng.annotations.Test;

public class CreateObjectProgrammWorkPWstatusInDev extends TestBase {

    @Test
    public void CreateOPRPRstInDev() {
        gotoResourse(baseURL);
        login("baykal01", "Orator16");
        choiceSection();
        choiceYear("2030");
        choiseProgramWork("PIRRoadFullRepair"); // "PIRRoadRepair" - еще одна программа работ, в которой сохраняются данные.
        createProgramWorkInSelectedYear();
        createObjectProgramWorkInDev();
    }

}
