package ru.risad.test;

// Generated by Selenium IDE
import org.testng.annotations.Test;

public class CreateObjectProgrammWorkinPIRRoadRepair extends TestBase {

    @Test
    public void atestCreateOPWbyFKUinPIRRoadRepair() {
        gotoResourse(baseURL);
        login("baykal01", "Orator16");
        choiceSection("Планирование");
        choiceYear("2020");
        choiseProgramWork("PIRRoadRepair"); // "PIRRoadRepair" - еще одна программа работ, в которой сохраняются данные.
        createProgramWorkIfNotCreatedLater();
        createObjectProgramWork();
        findNameObject(nameObject);
        clickFormationOfPW();
    }

    @Test
    public void checkCreatedOPWbyFDAinPIRRoadRepair() {
        gotoResourse(baseURL);
        login("fda", "vashkulat");
        choiceSection("Планирование");
        choiceYear("2020");
        choiseProgramWork("PIRRoadRepair");
        findNameObject(nameObject);
    }

    //---------------------------------------------------------------------------------

}
