package ru.risad.test;

// Generated by Selenium IDE
import org.testng.annotations.Test;

public class CreateObjectProgrammWorkinPIRRoadRepair extends TestBase {

    @Test
    public void testCreateOPWbyFKUinPIRRoadRepair() {
        //Создание ОПР под учетной записью с ролью "пользователь ФКУ"
        gotoResourse(baseURL);
        login("baykal01", "Orator16");
        choiceSection("Планирование");
        choiceYear("2020");
        choiseProgramWork("PIRRoadRepair"); // "PIRRoadFullRepair" - еще одна программа работ, в которой сохраняются данные.
        createProgramWorkIfNotCreatedLater();
        createObjectProgramWork();
        findNameObject(nameObject);
        clickFormationOfPW();

        logout();

        //Проверка созданного ОПР под учетной записью с ролью "пользователь ФДА"
        login("fda", "vashkulat");
        choiceSection("Планирование");
        choiceYear("2020");
        choiseProgramWork("PIRRoadRepair");
        findNameObject(nameObject);
    }

}
